### ISSUE TITLE
error

### ISSUE THREAD

**Issue by deperado007** [nikhilbarhate99/PPO-PyTorch#56]
problem:__init__() got an unexpected keyword argument 'tags'. how can i solve it?

**Comment by Merak2** [comment]
F:\Anaconda3\envs\ppo\python.exe C:/Users/Admin/Desktop/PPO/test.py
Traceback (most recent call last):
  File "C:/Users/Admin/Desktop/PPO/test.py", line 10, in <module>
    import roboschool
  File "F:\Anaconda3\envs\ppo\lib\site-packages\roboschool\__init__.py", line 71, in <module>
    tags={ "pg_complexity": 1*1000000 },
  File "F:\Anaconda3\envs\ppo\lib\site-packages\gym\envs\registration.py", line 514, in register
    spec = EnvSpec(id=full_id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'tags'

Process finished with exit code 1

I also have this problem, Could you help me?

**Comment by Marverlises** [comment]
I have encountered the same problem. Do you know how to solve it？I think that's because of the roc=boschool edition, but I'm not sure.

**Comment by Merak2** [comment]
> 

I did not solve it , and gave up .

**Comment by jean123456789-china** [comment]
Me too

**Comment by keerthanss** [comment]
Maybe relevant: https://github.com/openai/roboschool/issues/210?ref=pythonrepo.com
The library roboschool seems like it has certain issues on specific machines. However, the fix suggested there did not work for me.
